parent(volodymyr_br, oksana). % true
parent(volodymyr_br, galyna_au). % false
brother(svyatoslav, volodymyr_br). % true
brother(volodymyr_br, svyatoslav). % true
brother(roman, volodymyr_gr). % false
sister(svyatoslav, oksana). % false
grandMother(volodymyr_br, galyna_gr). % true
grandFather(roman, svyatoslav). % false
aunt(svyatoslav, galyna_au). % true
aunt(volodymyr_br, galyna_au). % true
aunt(galyna_gr, oksana). % false
cousin(svyatoslav, natalia). % true
cousin(oksana, svyatoslav). % false